# Generated by Django 4.1.2 on 2022-11-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.TextField()),
                ('Course_name', models.TextField()),
                ('Course_code', models.TextField()),
                ('Section', models.TextField()),
                ('Units', models.TextField()),
                ('Days_and_time', models.TextField()),
                ('Room', models.TextField()),
                ('Instructor', models.TextField()),
                ('Meeting_Dates', models.TextField()),
                ('Status', models.TextField()),
                ('Capacity', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
