# Generated by Django 4.1.2 on 2022-11-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_description',
            field=models.TextField(default='N/A'),
        ),
    ]
