# Generated by Django 4.1.2 on 2022-11-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ID',
        ),
        migrations.AddField(
            model_name='course',
            name='Course_ID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
